def getStationName(id):
    for t in list:
        if id == t[0]:
            return t[1]
    return id

list = [ \
("ag","AGGO"), \
("ai","AIRA"), \
("ap","ALGOPARK"), \
("ar","ARECIBO"), \
("tl","ARIES_4M"), \
("yk","ARIES_9M"), \
("at","ATCA"), \
("bd","BADARY"), \
("br","BR-VLBA"), \
("ce","CEBRER26"), \
("cd","CEDUNA"), \
("cc","CHICHI10"), \
("ch","CHLBOLTN"), \
("sm","CRIMEA"), \
("sb","CTVA"), \
("a13","DSS13"), \
("a15","DSS15"), \
("a45","DSS45"), \
("a6a","DSS65A"), \
("eb","EFLSBERG"), \
("fd","FD-VLBA"), \
("ft","FORTLEZA"), \
("gs","GGAO12M"), \
("gc","GILCREEK"), \
("a14","GOLDMARS"), \
("gv","GOLDVENU"), \
("hh","HARTRAO"), \
("ht","HART15M"), \
("hc","HATCREEK"), \
("hs","HAYSTACK"), \
("hn","HN-VLBA"), \
("hb","HOBART12"), \
("ho","HOBART26"), \
("is","ISHIOKA"), \
("it","ITAPETGA"), \
("jb","JODRELL2"), \
("kb","KASHIM34"), \
("k1","KASHIM11"), \
("ke","KATH12M"), \
("ku","KAUAI"), \
("kk","KOKEE"), \
("k2","KOKEE12M"), \
("kt","KITTPEAK"), \
("km","KUNMING"), \
("kp","KP-VLBA"), \
("kg","KOGANEI"), \
("kw","KWAJAL26"), \
("la","LA-VLBA"), \
("ro","MADRID64"), \
("mr","MARCUS"), \
("md","MARPOINT"), \
("ma","MATERA"), \
("mc","MEDICINA"), \
("mh","METSAHOV"), \
("mi","MIAMI20"), \
("mu","MIURA"), \
("mz","MIZUSGSI"), \
("mn","MIZNAO10"), \
("mk","MK-VLBA"), \
("mo","MOJAVE12"), \
("mp","MOPRA"), \
("nl","NL-VLBA"), \
("no","NOBEYA45"), \
("nt","NOTO"), \
("g3","NRAO85_3"), \
("gb","NRAO_140"), \
("gt","GBT_VLBA"), \
("gn","NRAO20"), \
("ny","NYALES20"), \
("oh","OHIGGINS"), \
("on","ONSALA60"), \
("o8","ONSALA85"), \
("gg","ORION_5M"), \
("ov","OV-VLBA"), \
("oo","OVRO_130"), \
("pa","PARKES"), \
("pe","PENTCTON"), \
("pt","PIETOWN"), \
("qb","QUABBIN"), \
("yj","RAEGYEB"), \
("a61","ROBLED32"), \
("st","SANTIA12"), \
("sc","SC-VLBA"), \
("s3","SINTOTU3"), \
("kv","SEJONG"), \
("sh","SESHAN25"), \
("se","SEST"), \
("sy","SYOWA"), \
("sv","SVETLOE"), \
("ta","TATEYAMA"), \
("t6","TIANMA65"), \
("ti","TIDBIN64"), \
("tc","TIGO"), \
("tr","TORUN"), \
("ts","TSUKUB32"), \
("uc","UCHINOUR"), \
("ur","URUMQI"), \
("us","USSURISK"), \
("vs","VERAISGK"), \
("vm","VERAMZSW"), \
("y1","VLA"), \
("ww","WARK12M"), \
("wf","WESTFORD"), \
("wb","WSTRBORK"), \
("wn","WETTZ13N"), \
("ws","WETTZ13S"), \
("wz","WETTZELL"), \
("yg","YARRA12M"), \
("ys","YEBES40M"), \
("zc","ZELENCHK")]
