program name
use mpi
implicit none

    ! type declaration statements
    INTEGER                :: IERR, COMM, NEWCOMM, RANK, NSIZE, INFO, ROOT
    INTEGER                :: COUNT, DISCONNECT, BUF(256)
    INTEGER                :: DATATYPE, SOURCE, TAG, STATUS(MPI_STATUS_SIZE)
    CHARACTER(255)         :: PORTNAME, SERVICE_NAME

    ROOT = 0
    COUNT = 256
    DISCONNECT = 999
    PORTNAME="localhost:55555"
    SERVICE_NAME = "TEST"

    ! executable statements
    CALL MPI_INIT(IERR)

    CALL MPI_COMM_RANK(MPI_COMM_WORLD, RANK, IERR)
    CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NSIZE, IERR)

    print *, "COMM: ", MPI_COMM_WORLD
    print *, "NEWCOMM: ", NEWCOMM

   ! CALL MPI_LOOKUP_NAME(SERVICE_NAME, MPI_INFO_NULL, PORTNAME, IERR)
    CALL MPI_COMM_CONNECT(PORTNAME, MPI_INFO_NULL, ROOT, MPI_COMM_WORLD, NEWCOMM, IERR)

    CALL MPI_SEND(BUF, SIZE(BUF)+1, MPI_INT, 0, 100, MPI_COMM_WORLD, IERR)

    CALL MPI_BARRIER(MPI_COMM_WORLD, IERR)

    IF (RANK .EQ. ROOT) THEN
        print *, "Disconnect"
        CALL MPI_SEND(BUF, COUNT, MPI_INT, 0, 999, MPI_COMM_WORLD, IERR)
    ENDIF

    CALL MPI_COMM_DISCONNECT(NEWCOMM, IERR)
    CALL MPI_FINALIZE(IERR)
    STOP

end program name

