program main
use mpi
implicit none

    ! type declaration statements
    INTEGER                :: IERR, COMM, NEWCOMM, RANK, NSIZE, INFO, ROOT
    INTEGER                :: COUNT, DISCONNECT, BUF(256)
    INTEGER                :: DATATYPE, SOURCE, TAG, STATUS(MPI_STATUS_SIZE)
    CHARACTER(255)         :: PORTNAME, SERVICE_NAME

    ROOT = 0
    COUNT = 256
    DISCONNECT = 999
    PORTNAME="localhost:55555"
    SERVICE_NAME = "TEST"

    ! executable statements
    CALL MPI_INIT(IERR)

    CALL MPI_COMM_RANK(MPI_COMM_WORLD, RANK, IERR)
    CALL MPI_COMM_SIZE(MPI_COMM_WORLD, NSIZE, IERR)

    IF (RANK .EQ. ROOT) THEN
        CALL MPI_OPEN_PORT(MPI_INFO_NULL, PORTNAME, IERR)
       ! CALL MPI_PUBLISH_NAME(SERVICE_NAME, MPI_INFO_NULL, PORTNAME, IERR)
    ENDIF

    CALL MPI_COMM_ACCEPT(PORTNAME, MPI_INFO_NULL, ROOT, MPI_COMM_WORLD, NEWCOMM, IERR)
    DO WHILE(.TRUE.)
        CALL MPI_RECV(BUF, COUNT, DATATYPE, SOURCE, TAG, MPI_COMM_WORLD, STATUS, IERR)
        PRINT *, "HELLO WORLD"

        IF(STATUS(TAG) .EQ. DISCONNECT) THEN
            IF (RANK .EQ. ROOT) THEN
                CALL MPI_CLOSE_PORT(PORTNAME, IERR)
                CALL MPI_UNPUBLISH_NAME(SERVICE_NAME, INFO, PORTNAME, IERR)
            ENDIF
        ENDIF
    ENDDO

    CALL MPI_FINALIZE(IERR)
    STOP

end program main

